version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: hello-world-demo
    container_name: hello-world-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - hello-world-networks

  db:
    image: mysql:5.7
    container_name: hello-world-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - hello-world-networks

  nginx:
    image: nginx:alpine
    container_name: hello-world-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - hello-world-networks

networks:
  hello-world-networks:
    driver: bridge
